"""AnimeJaNai mpv backend. No GLSL — launch the bundle so vf_animejanai loads Balanced."""

from __future__ import annotations

import threading
from collections.abc import Callable
from pathlib import Path

from app.settings import (
    animejanai_portable_config,
    appdata_dir,
    resolve_animejanai_binary,
)
from app.winproc import format_cmd, run_logged

LogCb = Callable[[str], None]
ProgressCb = Callable[[str, float | None], None]

ENGINE_NOTE = (
    "TensorRT engine builds once and can take several minutes. "
    "Playback/encode pauses on first resolution until the engine is ready."
)

BALANCED_CONF_NAME = "animejanai_balanced.conf"

# Shift+2 equivalent: the bundle's mpv-animejanai.conf already ends with
# profile=upscale-on (slot 1002 Balanced). Do NOT set profile=upscale-on on
# the CLI or in this include — mpv.net treats it as a property and loops.
# Encoding must override vo=gpu-next from the bundle with vo=lavc.
BALANCED_CONF_BODY = """# Generated by ClientSR Dump Lab. Do not pass GLSL.
# Bundle already loads Balanced (slot 1002 / Shift+2) via profile=upscale-on.
vo=lavc
save-position-on-quit=no
osc=no
osd-level=0
"""


class AnimeJaNaiError(RuntimeError):
    pass


def write_balanced_conf() -> Path:
    path = appdata_dir() / BALANCED_CONF_NAME
    path.write_text(BALANCED_CONF_BODY, encoding="utf-8")
    return path


def model_ready_animejanai(configured: Path) -> str | None:
    binary = resolve_animejanai_binary(configured)
    if binary is None:
        folder = configured.parent if configured.suffix else configured
        return (
            "ANIMEJANAI_BAL_4080: AnimeJaNai CLI mpv.exe missing. "
            f"Need the bundle's mpv.exe (not mpvnet.exe) at {configured} "
            f"or in {folder}. mpvnet is a GUI and will not finish an encode."
        )
    portable = animejanai_portable_config(binary)
    if not portable.is_dir():
        return (
            f"ANIMEJANAI_BAL_4080: portable_config missing: {portable} "
            "(needed so the native 2× filter + Balanced profile load)"
        )
    return None


def build_animejanai_cmd(
    binary: Path,
    portable: Path,
    include_conf: Path,
    source: Path,
    tmp_mkv: Path,
    target_w: int,
    target_h: int,
    fps_str: str,
) -> list[str]:
    """Launch the AnimeJaNai mpv so its built-in 2× filter + Balanced profile load.

    Do not pass --glsl-shaders. Do not use --no-config (that would drop vf_animejanai).
    --vf-add (not --vf) so we do not replace the @aji filter.
    """
    cmd = [
        str(binary),
        f"--config-dir={portable}",
        f"--include={include_conf}",
        "--keep-open=no",
        "--idle=no",
        "--no-audio",
        "--aid=no",
        "--sid=no",
        "--no-sub",
        "--osc=no",
        "--osd-level=0",
        # portable_config sets vo=gpu-next; encoding must use lavc or the VO window fails.
        "--vo=lavc",
        "--untimed",
        "--video-sync=desync",
        "--framedrop=no",
        "--hr-seek-framedrop=no",
        "--save-position-on-quit=no",
        f"--vf-add=gpu=w={target_w}:h={target_h}",
        f"--o={tmp_mkv}",
        "--of=matroska",
        "--ovc=libx264",
        "--ovcopts=crf=16,preset=fast",
    ]
    # --ofps/--oautofps were removed from mpv 0.41 encoding. ffmpeg conform
    # locks CFR to fps_str (vf=gpu can stretch timestamps on heavy dumps).
    cmd.append(str(source))
    return cmd


def render_animejanai(
    configured: Path,
    source: Path,
    tmp_mkv: Path,
    target_w: int,
    target_h: int,
    fps_str: str,
    *,
    cancel_event: threading.Event | None = None,
    log: LogCb | None = None,
    progress: ProgressCb | None = None,
) -> list[str]:
    err = model_ready_animejanai(configured)
    if err:
        raise AnimeJaNaiError(err)

    binary = resolve_animejanai_binary(configured)
    assert binary is not None
    if binary.name.lower() in {"mpvnet.exe", "mpvnet.com"}:
        raise AnimeJaNaiError(
            "refusing mpvnet for dumps — it is a GUI and does not exit in encode mode. "
            f"Use the bundle mpv.exe instead of {binary}"
        )
    portable = animejanai_portable_config(binary)
    include_conf = write_balanced_conf()
    tmp_mkv.parent.mkdir(parents=True, exist_ok=True)

    cmd = build_animejanai_cmd(
        binary, portable, include_conf, source, tmp_mkv, target_w, target_h, fps_str
    )
    if log:
        log(ENGINE_NOTE)
        log(f"AnimeJaNai binary: {binary}")
        log(f"AnimeJaNai portable_config: {portable}")
        log(f"include (Balanced / Shift+2 / slot 1002): {include_conf}")
        log(f"mpv: {format_cmd(cmd)}")

    def on_err(line: str) -> None:
        if not line.strip():
            return
        low = line.lower()
        if progress is not None and (
            "%" in line or "AV:" in line or "frame" in low or "engine" in low
        ):
            progress(f"animejanai {line.strip()[:160]}", None)
        elif log and any(
            k in low
            for k in ("error", "fatal", "failed", "tensorrt", "engine", "building")
        ):
            log(f"  animejanai: {line}")

    rc, _out, err_lines = run_logged(
        cmd,
        cancel_event=cancel_event,
        on_stderr=on_err,
        on_stdout=on_err,
        hide_window=False,
        cwd=binary.parent,
    )
    if cancel_event is not None and cancel_event.is_set():
        raise AnimeJaNaiError("cancelled")
    if rc != 0 or not tmp_mkv.is_file() or tmp_mkv.stat().st_size == 0:
        tail = "\n".join((_out + err_lines)[-40:]).strip()
        raise AnimeJaNaiError(
            f"AnimeJaNai render failed (exit {rc}). binary={binary} "
            + (tail[-800:] if tail else "no stderr — is aji.dll / TensorRT runtime present?")
        )
    return cmd
