"""Windowed live playback using the same mpv binaries and shaders as dumps.

Encode flags (--o, --ovc, --of, --vo=lavc, --untimed, --no-audio, --hwdec=no)
stay dump-only.

Live decode is split by mode (intentional — two different GPU paths):

- LIVE_NONE: --hwdec=d3d11va --gpu-api=d3d11 (matches vo=gpu-next + d3d11,
  which is what Chrome uses on Windows). Do not pass --hwdec=nvdec here:
  raw CUDA nvdec often fails silently on that VO and mpv stays on software.
  Fallback once: d3d11va-copy, then nvdec-copy. Never stay on hwdec=no
  without a visible log line. No --glsl-shaders, no AnimeJaNai, no --vf=gpu,
  no --untimed. --vo=gpu-next, --force-window=yes, and audio stay on.
- Catalog AI models: --hwdec=nvdec-copy so GLSL / vf=gpu / AnimeJaNai can hook
  the texture. Fallback d3d11va-copy. Do not switch these to plain nvdec.

The extra GPU copy is a cost of hooking client shaders, not of watching the
file. A fair no-AI baseline must not pay that copy.
"""

from __future__ import annotations

import re
import subprocess
import threading
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from app.backend_animejanai import ENGINE_NOTE, model_ready_animejanai
from app.backend_mpv import (
    BackendError,
    glsl_shaders_arg,
    model_ready_glsl,
    resolve_shader_chain,
)
from app.catalog import MODELS, ModelSpec
from app.settings import (
    DEFAULT_LIVE_HWDEC,
    DEFAULT_LIVE_NONE_GPU_API,
    DEFAULT_LIVE_NONE_HWDEC,
    LIVE_HWDEC_CHOICES,
    LIVE_HWDEC_FALLBACK,
    LIVE_NONE_HWDEC_FALLBACK,
    LIVE_NONE_HWDEC_LAST,
    animejanai_portable_config,
    appdata_dir,
    resolve_animejanai_binary,
)
from app.winproc import popen

LIVE_CONF_NAME = "animejanai_balanced_live.conf"
HWDEC_PROBE_NAME = "clientsr_hwdec_probe.lua"

# Prints hwdec-current after the decoder has had a chance to attach. Silent
# nvdec/d3d11va failure otherwise looks like a healthy session (high CPU).
HWDEC_PROBE_LUA = """-- Generated by ClientSR Dump Lab. Do not pass GLSL.
local sent = false
local function send(v)
    if sent then return end
    sent = true
    if v == nil or v == "" then
        v = "no"
    end
    mp.msg.warn("[clientsr] hwdec-current=" .. v)
end
mp.register_event("playback-restart", function()
    mp.add_timeout(0.8, function()
        send(mp.get_property("hwdec-current"))
    end)
end)
"""

# Encode-only BALANCED_CONF_BODY sets vo=lavc. Live must not: the bundle keeps
# vo=gpu-next and Balanced / slot 1002 / profile=upscale-on.
# Do not vf-add=gpu here either — that filter is the encode-path canvas lock.
LIVE_CONF_BODY = """# Generated by ClientSR Dump Lab for live playback. Do not pass GLSL.
# Bundle already loads Balanced (slot 1002 / Shift+2) via profile=upscale-on.
# Encoding uses lavc output and vf=gpu; this live include must not.
save-position-on-quit=no
"""

GLSL_LIVE_TOKENS = frozenset(m.token for m in MODELS if m.backend == "mpv_glsl")

# Live-only. Never a dump catalog token — no MP4, no sidecar.
TOKEN_LIVE_NONE = "LIVE_NONE"
LIVE_NONE_LABEL = "None — native (no AI, hw decode)"

# mpv ERR/WARN lines that mean the requested --hwdec= did not init.
_HWDEC_FAIL_MARKERS = (
    "failed to initialize a hardware decoder",
    "failed to initialize nvdec",
    "could not initialize nvdec",
    "failed to open nvdec",
    "cannot load nvcuda",
    "cannot load nvcuvid",
    "no cuda-capable device",
    "cuda_error_no_device",
    "could not create cuda context",
    "failed to create cuda context",
    "nvdec-copy failed",
    "nvdec failed",
    "failed to initialize d3d11va",
    "could not initialize d3d11va",
    "d3d11va-copy failed",
    "failed to initialize d3d11va-copy",
    "could not initialize d3d11va-copy",
    "failed to create d3d11 device",
    "d3d11va failed",
    "hwdec failed",
)

_HWDEC_ATTACHED_RE = re.compile(
    r"using hardware decoding \(([^)]+)\)",
    re.IGNORECASE,
)
_HWDEC_CURRENT_RE = re.compile(
    r"\[clientsr\]\s*hwdec-current=(\S*)",
    re.IGNORECASE,
)
_SOFTWARE_HWDEC = frozenset({"no", "none", ""})


class LiveError(RuntimeError):
    pass


@dataclass
class LiveLaunch:
    cmd: list[str]
    cwd: Path | None
    token: str
    hwdec: str = DEFAULT_LIVE_HWDEC
    hwdec_fallbacks: list[str] = field(default_factory=list)
    copy_required: bool = True
    gpu_api: str | None = None
    notes: list[str] = field(default_factory=list)
    engine_note: bool = False
    mpvnet_fallback: bool = False

    def hwdec_log_line(self) -> str:
        """Documented live-mode hwdec line (token + why copy is or is not paid)."""
        if self.token == TOKEN_LIVE_NONE:
            gpu = f" --gpu-api={self.gpu_api}" if self.gpu_api else ""
            if self.copy_required or "copy" in self.hwdec:
                return (
                    f"live NONE intended --hwdec={self.hwdec}{gpu} "
                    "(copy forced on None baseline)"
                )
            return (
                f"live NONE intended --hwdec={self.hwdec}{gpu} "
                "(no copy, Chrome-like baseline)"
            )
        return (
            f"live {self.token} intended --hwdec={self.hwdec} "
            "(copy required for shaders)"
        )


def normalize_live_hwdec(value: str | None) -> str:
    """AI live sessions only. LIVE_NONE does not go through this."""
    raw = (value or DEFAULT_LIVE_HWDEC).strip().lower()
    if raw in LIVE_HWDEC_CHOICES:
        return raw
    return DEFAULT_LIVE_HWDEC


def resolve_live_hwdec_plan(
    *,
    passthrough: bool,
    configured: str | None = None,
    none_force_copy: bool = False,
) -> tuple[str, list[str], bool]:
    """Return (hwdec, fallbacks, copy_required).

    LIVE_NONE is locked to d3d11va (gpu-next + d3d11, Chrome-like) unless
    none_force_copy. Catalog AI models use live_hwdec / nvdec-copy. Fallbacks
    never mix the two families: NONE goes d3d11va → d3d11va-copy → nvdec-copy;
    AI goes nvdec-copy → d3d11va-copy. Do not pass plain nvdec on NONE while
    vo is gpu-next/d3d11. Do not fall back to hwdec=no.
    """
    if passthrough:
        if none_force_copy:
            return (
                LIVE_NONE_HWDEC_FALLBACK,
                [LIVE_NONE_HWDEC_LAST],
                True,
            )
        return (
            DEFAULT_LIVE_NONE_HWDEC,
            [LIVE_NONE_HWDEC_FALLBACK, LIVE_NONE_HWDEC_LAST],
            False,
        )
    hwdec = normalize_live_hwdec(configured)
    fallbacks = [LIVE_HWDEC_FALLBACK] if hwdec == DEFAULT_LIVE_HWDEC else []
    return hwdec, fallbacks, True


def live_decode_args(hwdec: str) -> list[str]:
    """GPU decode + presentation flags for every live session.

    Two decode paths (caller chooses hwdec):

    - d3d11va (LIVE_NONE): matches gpu-next + d3d11, closest to Chrome on
      Windows. No shader hooks. Do not use raw nvdec on this VO.
    - nvdec-copy (catalog AI): NVDEC then a copy into a shader-safe buffer so
      GLSL, vf=gpu, and AnimeJaNai can hook the texture. Plain nvdec often
      breaks those hooks.

    Do not pass --untimed on live.
    """
    probe = write_hwdec_probe_script()
    return [
        f"--hwdec={hwdec}",
        "--hwdec-codecs=h264,hevc,av1,vp9,avc,mpeg2",
        "--vd-lavc-dr=yes",
        "--video-sync=audio",
        "--framedrop=vo",
        "--interpolation=no",
        "--terminal=yes",
        "--msg-color=no",
        f"--scripts={probe.as_posix()}",
    ]


def cmd_with_hwdec(cmd: list[str], hwdec: str) -> list[str]:
    """Copy argv, replacing any --hwdec=… (or inserting before the source path)."""
    out: list[str] = []
    replaced = False
    skip_next = False
    for arg in cmd:
        if skip_next:
            skip_next = False
            continue
        if arg.startswith("--hwdec="):
            if not replaced:
                out.append(f"--hwdec={hwdec}")
                replaced = True
            continue
        if arg == "--hwdec":
            if not replaced:
                out.append(f"--hwdec={hwdec}")
                replaced = True
            skip_next = True
            continue
        out.append(arg)
    if not replaced:
        if out:
            out.insert(-1, f"--hwdec={hwdec}")
        else:
            out.append(f"--hwdec={hwdec}")
    return out


def is_software_hwdec(value: str | None) -> bool:
    return (value or "no").strip().lower() in _SOFTWARE_HWDEC


def is_hwdec_init_failure(line: str) -> bool:
    low = line.lower()
    if any(m in low for m in _HWDEC_FAIL_MARKERS):
        return True
    if "using software decoding" in low or "falling back to software decoding" in low:
        return True
    attached = parse_attached_hwdec(line)
    if attached is not None and is_software_hwdec(attached):
        return True
    return False


def parse_attached_hwdec(line: str) -> str | None:
    """mpv 'Using hardware decoding (X)' / probe script / software — what attached."""
    m = _HWDEC_CURRENT_RE.search(line)
    if m:
        raw = m.group(1).strip()
        if raw.startswith("${"):
            return None
        if is_software_hwdec(raw):
            return "no"
        return raw
    m = _HWDEC_ATTACHED_RE.search(line)
    if m:
        return m.group(1).strip()
    low = line.lower()
    if "using software decoding" in low or "falling back to software decoding" in low:
        return "no"
    return None


def write_live_conf() -> Path:
    path = appdata_dir() / LIVE_CONF_NAME
    path.write_text(LIVE_CONF_BODY, encoding="utf-8")
    return path


def write_hwdec_probe_script() -> Path:
    path = appdata_dir() / HWDEC_PROBE_NAME
    path.write_text(HWDEC_PROBE_LUA, encoding="utf-8")
    return path


def _find_mpvnet(configured: Path) -> Path | None:
    folder = configured.parent if configured.suffix else configured
    for name in ("mpvnet.exe", "mpvnet.com"):
        cand = folder / name
        try:
            if cand.is_file():
                return cand
        except OSError:
            continue
    return None


def resolve_animejanai_live_binary(configured: Path) -> tuple[Path | None, bool]:
    """Prefer bundle mpv.exe (same as dumps). mpvnet is a live-only fallback."""
    binary = resolve_animejanai_binary(configured)
    if binary is not None:
        return binary, False
    net = _find_mpvnet(configured)
    if net is not None:
        return net, True
    return None, False


def model_ready_passthrough(mpv: Path) -> str | None:
    if not mpv.is_file():
        return f"{TOKEN_LIVE_NONE}: plain mpv missing: {mpv}"
    return None


def model_ready_live(
    spec: ModelSpec | None,
    mpv: Path,
    shaders_dir: Path,
    animejanai_configured: Path,
) -> str | None:
    """None if this model can play live. Errors reuse dump readiness strings."""
    if spec is None or spec.token == TOKEN_LIVE_NONE:
        return model_ready_passthrough(mpv)
    if spec.backend == "mpv_glsl":
        return model_ready_glsl(spec, mpv, shaders_dir)
    if spec.backend == "animejanai":
        err = model_ready_animejanai(animejanai_configured)
        if err is None:
            return None
        if _find_mpvnet(animejanai_configured) is not None:
            return None
        return err
    return f"{spec.token}: unknown backend {spec.backend}"


def build_passthrough_live_cmd(
    mpv: Path,
    source: Path,
    *,
    hwdec: str = DEFAULT_LIVE_NONE_HWDEC,
) -> list[str]:
    """Windowed source playback. No shaders, no vf=gpu, native window scale."""
    return [
        str(mpv),
        "--no-config",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        f"--gpu-api={DEFAULT_LIVE_NONE_GPU_API}",
        *live_decode_args(hwdec),
        f"--title=ClientSR live — {TOKEN_LIVE_NONE}",
        str(source),
    ]


def build_mpv_glsl_live_cmd(
    mpv: Path,
    source: Path,
    shaders: list[Path],
    target_w: int,
    target_h: int,
    token: str,
    *,
    hwdec: str = DEFAULT_LIVE_HWDEC,
) -> list[str]:
    return [
        str(mpv),
        "--no-config",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        "--gpu-api=auto",
        *live_decode_args(hwdec),
        f"--glsl-shaders={glsl_shaders_arg(shaders)}",
        f"--vf=gpu=w={target_w}:h={target_h}",
        f"--title=ClientSR live — {token}",
        str(source),
    ]


def build_animejanai_live_cmd(
    binary: Path,
    portable: Path,
    include_conf: Path,
    source: Path,
    target_w: int,
    target_h: int,
    *,
    hwdec: str = DEFAULT_LIVE_HWDEC,
) -> list[str]:
    """Windowed playback through the bundle's @aji filter + vo=gpu-next.

    Do not --vf-add=gpu. That filter is encode-only (vo=lavc): it opens a
    second libplacebo/Vulkan device, vf_animejanai then fails with
    "Failed to create inference context" and is disabled, and the leftover
    gpu filter converts CUDA frames to a black rgb0 canvas. @aji already
    outputs 2x; autofit sizes the window to that canvas.

    Do not --no-config (that would drop vf_animejanai). CLI --hwdec= wins
    over any hwdec the bundle config already set.
    """
    return [
        str(binary),
        f"--config-dir={portable}",
        f"--include={include_conf}",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        *live_decode_args(hwdec),
        "--save-position-on-quit=no",
        f"--autofit={target_w}x{target_h}",
        "--title=ClientSR live — ANIMEJANAI_BAL_4080",
        str(source),
    ]


def prepare_passthrough_live(
    source: Path,
    *,
    mpv: Path,
    force_copy: bool = False,
) -> LiveLaunch:
    """Build a no-model live argv. Does not spawn. Raises LiveError if not ready.

    LIVE_NONE is locked to d3d11va + gpu-api=d3d11 unless force_copy.
    live_hwdec in config.yaml does not apply here.
    """
    hwdec, fallbacks, copy_required = resolve_live_hwdec_plan(
        passthrough=True, none_force_copy=force_copy
    )
    err = model_ready_passthrough(mpv)
    if err:
        raise LiveError(err)
    if not source.is_file():
        raise LiveError(f"source missing: {source}")
    return LiveLaunch(
        cmd=build_passthrough_live_cmd(mpv, source, hwdec=hwdec),
        cwd=None,
        token=TOKEN_LIVE_NONE,
        hwdec=hwdec,
        hwdec_fallbacks=list(fallbacks),
        copy_required=copy_required,
        gpu_api=DEFAULT_LIVE_NONE_GPU_API,
        notes=[
            "LIVE_NONE: no shaders, no AnimeJaNai, no vf=gpu — "
            "native window scale (Chrome-like baseline)"
        ],
    )


def prepare_live(
    spec: ModelSpec | None,
    source: Path,
    target_w: int,
    target_h: int,
    *,
    mpv: Path,
    shaders_dir: Path,
    animejanai_configured: Path,
    hwdec: str = DEFAULT_LIVE_HWDEC,
    none_force_copy: bool = False,
) -> LiveLaunch:
    """Build a live argv. Does not spawn. Raises LiveError if not ready.

    hwdec (live_hwdec) applies to catalog AI models only. LIVE_NONE stays
    d3d11va + gpu-api=d3d11 unless none_force_copy.
    """
    if spec is None or spec.token == TOKEN_LIVE_NONE:
        return prepare_passthrough_live(source, mpv=mpv, force_copy=none_force_copy)
    hwdec, fallbacks, copy_required = resolve_live_hwdec_plan(
        passthrough=False, configured=hwdec
    )
    err = model_ready_live(spec, mpv, shaders_dir, animejanai_configured)
    if err:
        raise LiveError(err)
    if not source.is_file():
        raise LiveError(f"source missing: {source}")
    if target_w <= 0 or target_h <= 0:
        raise LiveError(f"{spec.token}: invalid 2× target {target_w}x{target_h}")

    if spec.backend == "mpv_glsl":
        if spec.token not in GLSL_LIVE_TOKENS:
            raise LiveError(f"{spec.token}: not a GLSL live model")
        try:
            shaders, shader_notes = resolve_shader_chain(
                shaders_dir,
                spec.shaders,
                fuzzy=spec.token.startswith("ANIME4K"),
            )
        except BackendError as exc:
            raise LiveError(f"{spec.token}: {exc}") from exc
        cmd = build_mpv_glsl_live_cmd(
            mpv, source, shaders, target_w, target_h, spec.token, hwdec=hwdec
        )
        return LiveLaunch(
            cmd=cmd,
            cwd=None,
            token=spec.token,
            hwdec=hwdec,
            hwdec_fallbacks=list(fallbacks),
            copy_required=copy_required,
            notes=[f"{spec.token} shaders: " + " → ".join(shader_notes)],
        )

    if spec.backend == "animejanai":
        binary, mpvnet_fallback = resolve_animejanai_live_binary(animejanai_configured)
        if binary is None:
            raise LiveError(model_ready_animejanai(animejanai_configured) or "AnimeJaNai missing")
        portable = animejanai_portable_config(binary)
        if not portable.is_dir():
            raise LiveError(
                f"ANIMEJANAI_BAL_4080: portable_config missing: {portable} "
                "(needed so the native 2× filter + Balanced profile load)"
            )
        include_conf = write_live_conf()
        cmd = build_animejanai_live_cmd(
            binary, portable, include_conf, source, target_w, target_h, hwdec=hwdec
        )
        notes = [
            f"AnimeJaNai binary: {binary}",
            f"AnimeJaNai portable_config: {portable}",
            f"include (live Balanced / Shift+2 / slot 1002): {include_conf}",
        ]
        if mpvnet_fallback:
            notes.append(
                f"warning: live AnimeJaNai falling back to {binary.name} — "
                "dumps still require bundle mpv.exe. If the filter fails to load, install the bundle mpv.exe."
            )
        return LiveLaunch(
            cmd=cmd,
            cwd=binary.parent,
            token=spec.token,
            hwdec=hwdec,
            hwdec_fallbacks=list(fallbacks),
            copy_required=copy_required,
            notes=notes,
            engine_note=True,
            mpvnet_fallback=mpvnet_fallback,
        )

    raise LiveError(f"{spec.token}: unknown backend {spec.backend}")


def _drain_stdio(
    proc: subprocess.Popen[str],
    on_line: Callable[[str], None] | None = None,
) -> None:
    """popen() pipes stdout/stderr; unread pipes stall a long-lived mpv."""

    def _read(stream) -> None:
        if stream is None:
            return
        try:
            for raw in iter(stream.readline, ""):
                line = raw.rstrip("\r\n")
                if on_line is not None and line.strip():
                    on_line(line)
        except Exception:
            pass
        try:
            stream.close()
        except Exception:
            pass

    threading.Thread(
        target=_read, args=(proc.stdout,), daemon=True, name="live-stdout"
    ).start()
    threading.Thread(
        target=_read, args=(proc.stderr,), daemon=True, name="live-stderr"
    ).start()


def start_live_process(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    on_line: Callable[[str], None] | None = None,
) -> subprocess.Popen[str]:
    """Visible Windows mpv. Never CREATE_NO_WINDOW. Never shell=True."""
    proc = popen(cmd, hide_window=False, cwd=cwd)
    _drain_stdio(proc, on_line=on_line)
    return proc


# Re-export so callers can log the TensorRT stall once.
__all__ = [
    "ENGINE_NOTE",
    "GLSL_LIVE_TOKENS",
    "LIVE_HWDEC_CHOICES",
    "LIVE_HWDEC_FALLBACK",
    "LIVE_NONE_LABEL",
    "LiveError",
    "LiveLaunch",
    "TOKEN_LIVE_NONE",
    "build_animejanai_live_cmd",
    "build_mpv_glsl_live_cmd",
    "build_passthrough_live_cmd",
    "cmd_with_hwdec",
    "is_hwdec_init_failure",
    "is_software_hwdec",
    "live_decode_args",
    "model_ready_live",
    "model_ready_passthrough",
    "normalize_live_hwdec",
    "parse_attached_hwdec",
    "prepare_live",
    "prepare_passthrough_live",
    "resolve_animejanai_live_binary",
    "resolve_live_hwdec_plan",
    "start_live_process",
    "write_hwdec_probe_script",
    "write_live_conf",
]
