"""Windowed live playback using the same mpv binaries and shaders as dumps.

Encode flags (--o, --ovc, --of, --vo=lavc, --untimed, --no-audio) stay dump-only.
"""

from __future__ import annotations

import subprocess
import threading
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from app.backend_animejanai import ENGINE_NOTE, model_ready_animejanai
from app.backend_mpv import (
    BackendError,
    glsl_shaders_arg,
    model_ready_glsl,
    resolve_shader_chain,
)
from app.catalog import MODELS, ModelSpec
from app.settings import (
    animejanai_portable_config,
    appdata_dir,
    resolve_animejanai_binary,
)
from app.winproc import popen

LIVE_CONF_NAME = "animejanai_balanced_live.conf"

# Encode-only BALANCED_CONF_BODY sets vo=lavc. Live must not: the bundle keeps
# vo=gpu-next and Balanced / slot 1002 / profile=upscale-on.
# Do not vf-add=gpu here either — that filter is the encode-path canvas lock.
LIVE_CONF_BODY = """# Generated by ClientSR Dump Lab for live playback. Do not pass GLSL.
# Bundle already loads Balanced (slot 1002 / Shift+2) via profile=upscale-on.
# Encoding uses lavc output and vf=gpu; this live include must not.
save-position-on-quit=no
"""

GLSL_LIVE_TOKENS = frozenset(m.token for m in MODELS if m.backend == "mpv_glsl")

# Live-only. Never a dump catalog token — no MP4, no sidecar.
TOKEN_LIVE_NONE = "NONE"
LIVE_NONE_LABEL = "None — no model (test)"


class LiveError(RuntimeError):
    pass


@dataclass
class LiveLaunch:
    cmd: list[str]
    cwd: Path | None
    token: str
    notes: list[str] = field(default_factory=list)
    engine_note: bool = False
    mpvnet_fallback: bool = False


def write_live_conf() -> Path:
    path = appdata_dir() / LIVE_CONF_NAME
    path.write_text(LIVE_CONF_BODY, encoding="utf-8")
    return path


def _find_mpvnet(configured: Path) -> Path | None:
    folder = configured.parent if configured.suffix else configured
    for name in ("mpvnet.exe", "mpvnet.com"):
        cand = folder / name
        try:
            if cand.is_file():
                return cand
        except OSError:
            continue
    return None


def resolve_animejanai_live_binary(configured: Path) -> tuple[Path | None, bool]:
    """Prefer bundle mpv.exe (same as dumps). mpvnet is a live-only fallback."""
    binary = resolve_animejanai_binary(configured)
    if binary is not None:
        return binary, False
    net = _find_mpvnet(configured)
    if net is not None:
        return net, True
    return None, False


def model_ready_passthrough(mpv: Path) -> str | None:
    if not mpv.is_file():
        return f"{TOKEN_LIVE_NONE}: plain mpv missing: {mpv}"
    return None


def model_ready_live(
    spec: ModelSpec | None,
    mpv: Path,
    shaders_dir: Path,
    animejanai_configured: Path,
) -> str | None:
    """None if this model can play live. Errors reuse dump readiness strings."""
    if spec is None or spec.token == TOKEN_LIVE_NONE:
        return model_ready_passthrough(mpv)
    if spec.backend == "mpv_glsl":
        return model_ready_glsl(spec, mpv, shaders_dir)
    if spec.backend == "animejanai":
        err = model_ready_animejanai(animejanai_configured)
        if err is None:
            return None
        if _find_mpvnet(animejanai_configured) is not None:
            return None
        return err
    return f"{spec.token}: unknown backend {spec.backend}"


def build_passthrough_live_cmd(mpv: Path, source: Path) -> list[str]:
    """Windowed source playback. No shaders, no vf=gpu, native resolution."""
    return [
        str(mpv),
        "--no-config",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        "--gpu-api=auto",
        "--hwdec=no",
        "--framedrop=vo",
        f"--title=ClientSR live — {TOKEN_LIVE_NONE}",
        str(source),
    ]


def build_mpv_glsl_live_cmd(
    mpv: Path,
    source: Path,
    shaders: list[Path],
    target_w: int,
    target_h: int,
    token: str,
) -> list[str]:
    return [
        str(mpv),
        "--no-config",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        "--gpu-api=auto",
        "--hwdec=no",
        "--framedrop=vo",
        f"--glsl-shaders={glsl_shaders_arg(shaders)}",
        f"--vf=gpu=w={target_w}:h={target_h}",
        f"--title=ClientSR live — {token}",
        str(source),
    ]


def build_animejanai_live_cmd(
    binary: Path,
    portable: Path,
    include_conf: Path,
    source: Path,
    target_w: int,
    target_h: int,
) -> list[str]:
    """Windowed playback through the bundle's @aji filter + vo=gpu-next.

    Do not --vf-add=gpu. That filter is encode-only (vo=lavc): it opens a
    second libplacebo/Vulkan device, vf_animejanai then fails with
    "Failed to create inference context" and is disabled, and the leftover
    gpu filter converts CUDA frames to a black rgb0 canvas. @aji already
    outputs 2x; autofit sizes the window to that canvas.
    """
    return [
        str(binary),
        f"--config-dir={portable}",
        f"--include={include_conf}",
        "--force-window=yes",
        "--keep-open=yes",
        "--idle=no",
        "--osc=yes",
        "--osd-level=1",
        "--vo=gpu-next",
        "--framedrop=vo",
        "--save-position-on-quit=no",
        f"--autofit={target_w}x{target_h}",
        "--title=ClientSR live — ANIMEJANAI_BAL_4080",
        str(source),
    ]


def prepare_passthrough_live(source: Path, *, mpv: Path) -> LiveLaunch:
    """Build a no-model live argv. Does not spawn. Raises LiveError if not ready."""
    err = model_ready_passthrough(mpv)
    if err:
        raise LiveError(err)
    if not source.is_file():
        raise LiveError(f"source missing: {source}")
    return LiveLaunch(
        cmd=build_passthrough_live_cmd(mpv, source),
        cwd=None,
        token=TOKEN_LIVE_NONE,
        notes=["passthrough: no shaders, no AnimeJaNai, native resolution (test)"],
    )


def prepare_live(
    spec: ModelSpec | None,
    source: Path,
    target_w: int,
    target_h: int,
    *,
    mpv: Path,
    shaders_dir: Path,
    animejanai_configured: Path,
) -> LiveLaunch:
    """Build a live argv. Does not spawn. Raises LiveError if not ready."""
    if spec is None or spec.token == TOKEN_LIVE_NONE:
        return prepare_passthrough_live(source, mpv=mpv)
    err = model_ready_live(spec, mpv, shaders_dir, animejanai_configured)
    if err:
        raise LiveError(err)
    if not source.is_file():
        raise LiveError(f"source missing: {source}")
    if target_w <= 0 or target_h <= 0:
        raise LiveError(f"{spec.token}: invalid 2× target {target_w}x{target_h}")

    if spec.backend == "mpv_glsl":
        if spec.token not in GLSL_LIVE_TOKENS:
            raise LiveError(f"{spec.token}: not a GLSL live model")
        try:
            shaders, shader_notes = resolve_shader_chain(
                shaders_dir,
                spec.shaders,
                fuzzy=spec.token.startswith("ANIME4K"),
            )
        except BackendError as exc:
            raise LiveError(f"{spec.token}: {exc}") from exc
        cmd = build_mpv_glsl_live_cmd(
            mpv, source, shaders, target_w, target_h, spec.token
        )
        return LiveLaunch(
            cmd=cmd,
            cwd=None,
            token=spec.token,
            notes=[f"{spec.token} shaders: " + " → ".join(shader_notes)],
        )

    if spec.backend == "animejanai":
        binary, mpvnet_fallback = resolve_animejanai_live_binary(animejanai_configured)
        if binary is None:
            raise LiveError(model_ready_animejanai(animejanai_configured) or "AnimeJaNai missing")
        portable = animejanai_portable_config(binary)
        if not portable.is_dir():
            raise LiveError(
                f"ANIMEJANAI_BAL_4080: portable_config missing: {portable} "
                "(needed so the native 2× filter + Balanced profile load)"
            )
        include_conf = write_live_conf()
        cmd = build_animejanai_live_cmd(
            binary, portable, include_conf, source, target_w, target_h
        )
        notes = [
            f"AnimeJaNai binary: {binary}",
            f"AnimeJaNai portable_config: {portable}",
            f"include (live Balanced / Shift+2 / slot 1002): {include_conf}",
        ]
        if mpvnet_fallback:
            notes.append(
                f"warning: live AnimeJaNai falling back to {binary.name} — "
                "dumps still require bundle mpv.exe. If the filter fails to load, install the bundle mpv.exe."
            )
        return LiveLaunch(
            cmd=cmd,
            cwd=binary.parent,
            token=spec.token,
            notes=notes,
            engine_note=True,
            mpvnet_fallback=mpvnet_fallback,
        )

    raise LiveError(f"{spec.token}: unknown backend {spec.backend}")


def _drain_stdio(
    proc: subprocess.Popen[str],
    on_line: Callable[[str], None] | None = None,
) -> None:
    """popen() pipes stdout/stderr; unread pipes stall a long-lived mpv."""

    def _read(stream) -> None:
        if stream is None:
            return
        try:
            for raw in iter(stream.readline, ""):
                line = raw.rstrip("\r\n")
                if on_line is not None and line.strip():
                    on_line(line)
        except Exception:
            pass
        try:
            stream.close()
        except Exception:
            pass

    threading.Thread(
        target=_read, args=(proc.stdout,), daemon=True, name="live-stdout"
    ).start()
    threading.Thread(
        target=_read, args=(proc.stderr,), daemon=True, name="live-stderr"
    ).start()


def start_live_process(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    on_line: Callable[[str], None] | None = None,
) -> subprocess.Popen[str]:
    """Visible Windows mpv. Never CREATE_NO_WINDOW. Never shell=True."""
    proc = popen(cmd, hide_window=False, cwd=cwd)
    _drain_stdio(proc, on_line=on_line)
    return proc


# Re-export so callers can log the TensorRT stall once.
__all__ = [
    "ENGINE_NOTE",
    "GLSL_LIVE_TOKENS",
    "LIVE_NONE_LABEL",
    "LiveError",
    "LiveLaunch",
    "TOKEN_LIVE_NONE",
    "build_animejanai_live_cmd",
    "build_mpv_glsl_live_cmd",
    "build_passthrough_live_cmd",
    "model_ready_live",
    "model_ready_passthrough",
    "prepare_live",
    "prepare_passthrough_live",
    "resolve_animejanai_live_binary",
    "start_live_process",
    "write_live_conf",
]
